/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdad2",
        "outline": "#64748b",
        "inverse-surface": "#0f172a",
        "surface-bright": "#f8fafc",
        "on-error": "#ffffff",
        "background": "#f8fafc",
        "on-tertiary-fixed-variant": "#83260e",
        "surface-dim": "#e2e8f0",
        "surface-container-highest": "#e6eefc",
        "surface-container-low": "#f1f5f9",
        "inverse-primary": "#bfdbfe",
        "on-surface-variant": "#475569",
        "on-primary": "#ffffff",
        "primary-fixed": "#dbeafe",
        "secondary-fixed": "#dbeafe",
        "secondary": "#3b82f6",
        "on-primary-container": "#0b3a8a",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a2",
        "primary-fixed-dim": "#bfdbfe",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e6eefc",
        "on-primary-fixed": "#0b3a8a",
        "secondary-fixed-dim": "#93c5fd",
        "surface-container-high": "#eef2ff",
        "secondary-container": "#c7ddff",
        "primary": "#1e3a8a",
        "on-background": "#0f172a",
        "tertiary": "#1e40af",
        "outline-variant": "#cbd5e1",
        "on-surface": "#0f172a",
        "on-error-container": "#93000a",
        "surface": "#f8fafc",
        "primary-container": "#93c5fd",
        "inverse-on-surface": "#f1f5f9",
        "on-tertiary-container": "#0b3a8a",
        "on-secondary-fixed": "#06276b",
        "on-secondary-container": "#1e3a8a",
        "on-secondary-fixed-variant": "#1e40af",
        "surface-container": "#eef2ff",
        "tertiary-container": "#bfdbfe",
        "on-primary-fixed-variant": "#0b3a8a",
        "on-tertiary-fixed": "#3c0700",
        "on-secondary": "#ffffff",
        "surface-tint": "#1e3a8a",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "20px",
        "xs": "4px",
        "md": "24px",
        "xl": "64px",
        "sm": "12px",
        "gutter": "16px",
        "base": "8px",
        "lg": "40px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
}
